name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Extract Channel from Version
        uses: actions-ecosystem/action-regex-match@v2
        id: match-channel
        with:
          text: ${{ github.ref }}
          regex: '(eap|beta|alpha)\d*$'

      - name: Publish to JetBrains Marketplace
        uses: gradle/gradle-build-action@v2
        with:
          arguments: signPlugin
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: build/distributions/*.zip

  sentry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          version: ${{ steps.tagName.outputs.tag }}
